Create Database DBNOTICE On (Name = DBNOTICE, FileName = "D:\Database\DBNOTICE.mdf",
Size = 5MB,MaxSize = Unlimited, FileGrowth = 2MB)
Log On (Name = DBNOTICE_log, FileName = "D:\Database\DBNOTICE_log.ldf",
Size = 4MB, MaxSize = Unlimited, FileGrowth =10%)
GO
--MaxSize=4GB
USE DBNOTICE
GO
CREATE TABLE NOTE(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Note NVARCHAR(MAX),
	NoteDate DATE,
	CreateDate DATETIME,
	CreateBy NVARCHAR(MAX)
)
GO
CREATE TABLE GALLERY(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Photo VARBINARY(MAX),
	CreateDate DATETIME,
	CreateBy NVARCHAR(MAX)
)
GO
CREATE TABLE LOVECOUNT(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(MAX),
	Photo VARBINARY(MAX),
	StartDate DATE,
	[Status] NVARCHAR(MAX),
	CreateDate DATETIME,
	CreateBy NVARCHAR(MAX)
)
GO
--CREATE TABLE LOVECOUNT(
--	ID INT IDENTITY(1,1) PRIMARY KEY,
--	MaleName NVARCHAR(MAX),
--	MalePhoto VARBINARY(MAX),
--	FemaleName NVARCHAR(MAX),
--	FemalePhoto VARBINARY(MAX),
--	StartDate DATE,
--	[Status] NVARCHAR(MAX),
--	CreateDate DATETIME,
--	CreateBy NVARCHAR(MAX)
--)
GO
CREATE TABLE PAYMENT(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PaymentDate DATE,
	Items NVARCHAR(MAX),
	Price MONEY,
	[Description] NVARCHAR(MAX),
	CreateDate DATETIME,
	CreateBy NVARCHAR(MAX)
)
GO
CREATE TABLE YOURPAYMENT(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PaymentDate DATE,
	Items NVARCHAR(MAX),
	Price MONEY,
	[Description] NVARCHAR(MAX),
	CreateDate DATETIME,
	CreateBy NVARCHAR(MAX)
)
GO
CREATE TABLE BANK(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	[Date] DATE,
	Amount MONEY,
	[Type] NVARCHAR(MAX),
	[Description] NVARCHAR(MAX),
	CreateDate DATETIME,
	CreateBy NVARCHAR(MAX)
)
GO
CREATE TABLE INCOME(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	IncomeDate DATE,
	Amount MONEY,
	IncomeFrom NVARCHAR(MAX),
	[Description] NVARCHAR(MAX),
	CreateDate DATETIME,
	CreateBy NVARCHAR(MAX)
)
GO
CREATE TABLE BANK_SAVING(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	[Date] DATE,
	Amount MONEY,
	[Type] NVARCHAR(MAX),
	[Description] NVARCHAR(MAX),
	CreateDate DATETIME,
	CreateBy NVARCHAR(MAX)
)
GO
CREATE TABLE ALLEVENT(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	EventDate DATE,
	EventName NVARCHAR(MAX),
	[Description] NVARCHAR(MAX),
	CreateDate DATETIME,
	CreateBy NVARCHAR(MAX)
)
GO
CREATE TABLE ABOUT(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Note NVARCHAR(MAX),
	CreateDate DATETIME,
	CreateBy NVARCHAR(MAX)
)
GO

